### ISSUE TITLE
By Reference TTL to be ISO format

### ISSUE THREAD

**Issue by richard-jones** [swordapp/swordv3#23]
Documentation just says "timestamp", but we should be clear that this is ISO-8601, big endian, UTC in full like "2021-07-01T07:00:00Z"

**Comment by alexdutton** [comment]
Worth referencing complete datetimes as defined in [W3C NOTE-datetime](https://www.w3.org/TR/NOTE-datetime), which is a subset of ISO-8601? (so that people don't think week dates or ordinal dates are acceptable)

**Comment by richard-jones** [comment]
-  [x] add https://www.w3.org/TR/NOTE-datetime to the references
-  [x] Everywhere that `timestamp` appears in the specification, note the format and link to the reference above
