### ISSUE TITLE
What happens to Temporary-URL after successful deposit

### ISSUE THREAD

**Issue by richard-jones** [swordapp/swordv3#31]
We should be clear about what the server's responsibilities are with the Temporary-URL after it has been deposited in the normal way.  Should the server keep it around for the maxIdle period anyway?  Should it be allowed to delete it straight away? (I think the latter, and we should basically make this up to the server to decide).

**Comment by alexdutton** [comment]
I'd say the former, as the client might expect to be able to use this to deposit the same file into multiple deposits?

The invenio implementation is sensible enough to reference the same underlying file in both deposited file records in this scenario.

**Comment by richard-jones** [comment]
- [x] add text to 16.8 to describe the continued retention of the temporary file
